services:
  - type: web
    name: rural-urban-web
    env: node
    plan: free
    rootDir: web
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://rural-urban-api.onrender.com
  - type: web
    name: rural-urban-api
    env: node
    plan: free
    rootDir: api
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
