services:
  - type: web
    name: rural-urban-web
    env: node
    plan: free
    rootDir: web
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://rural-urban-api.onrender.com
  - type: web
    name: rural-urban-api
    env: node
    plan: free
    rootDir: api
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./dev.db
      - key: STUN_URLS
        value: stun:stun.l.google.com:19302
